# Generated by Django 3.1.7 on 2021-06-17 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('fullName', models.CharField(blank=True, max_length=40, null=True)),
                ('pfp', models.ImageField(default='placeholder.jpg', upload_to='pfp', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='Profile Picture')),
                ('pgp', models.ImageField(default='placeholder.jpg', upload_to='pgp', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='Background Picture')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('b_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
